[build]
builder = "DOCKERFILE"
dockerfilePath = "railway.dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PORT = "8080"
JWT_SECRET = "your-super-secure-jwt-secret-key-at-least-32-characters-long-for-production"
CORS_ORIGIN = "https://frontend-production-97d2.up.railway.app"
