services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: comment_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - comment-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend_comment
      dockerfile: Dockerfile
      target: production
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/comment_system
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production-please-make-it-long-and-random
      - NODE_ENV=production
      - PORT=3001
      - PRISMA_CLIENT_ENGINE_TYPE=binary
      - CORS_ORIGIN=http://localhost:3000,http://frontend:3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - comment-network
    ports:
      - "3001:3001"
    volumes:
      - ./backend_comment/prisma:/app/prisma
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run start:prod
      "
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend_comment
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - comment-network

networks:
  comment-network:
    driver: bridge

volumes:
  postgres_data:
