[build]
builder = "DOCKERFILE"
dockerfilePath = "frontend.railway.dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PORT = "8080"
VITE_API_URL = "https://comment-system-backend-production.up.railway.app"
VITE_APP_NAME = "Comment System"
VITE_ENVIRONMENT = "production"
