[build]
builder = "DOCKERFILE"
dockerfilePath = "railway.dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PORT = "8080"
BACKEND_URL = "https://comment-system-production.up.railway.app"
